KLEE: NOTE: Using POSIX model: /home/shafi/klee_build/runtime/lib/libkleeRuntimePOSIX64_Debug+Asserts.bca
KLEE: NOTE: Using klee-uclibc : /home/shafi/klee_build/runtime/lib/klee-uclibc.bca
KLEE: output directory is "/home/shafi/Research/attack-synthesis-suite-c/stase/klee-out-43"
KLEE: Using Z3 solver backend
KLEE: Logging queries that reach solver in .smt2 format to /home/shafi/Research/attack-synthesis-suite-c/stase/klee-out-43/solver-queries.smt2

KLEE: Deterministic allocator: Using quarantine queue size 8
KLEE: Deterministic allocator: globals (start-address=0x74e947600000 size=10 GiB)
KLEE: Deterministic allocator: constants (start-address=0x74e6c7600000 size=10 GiB)
KLEE: Deterministic allocator: heap (start-address=0x73e6c7600000 size=1024 GiB)
KLEE: Deterministic allocator: stack (start-address=0x73c6c7600000 size=128 GiB)
KLEE: WARNING ONCE: calling external: syscall(16, 0, 21505, 127342682832896) at klee/runtime/POSIX/fd.c:997 10
KLEE: WARNING ONCE: Alignment of memory from call "malloc" is not modelled. Using alignment of 8.
KLEE: WARNING ONCE: calling __klee_posix_wrapped_main with extra arguments.
KLEE: WARNING ONCE: calling external: printf(128535878434816, 128538864779264) at ./../common.c:98 1
KLEE: ERROR: ./../testcases/CWE121_Stack_Based_Buffer_Overflow/s01/CWE121_Stack_Based_Buffer_Overflow__CWE129_fgets_01.c:49: ASSERTION FAIL: data >= 0 && data < (int)(sizeof(buffer) / sizeof(buffer[0])) && "Stack based buffer overflow check"
KLEE: NOTE: now ignoring this error at this location
KLEE: WARNING ONCE: silently concretizing (reason: external call) expression (ReadLSB w32 0 U0:[(Add w32 3
                             N0:(Extract w32 0 (Mul w64 4
                                                        (SExt w64 (ReadLSB w32 0 data)))))=0,
                    (Add w32 2 N0)=0,
                    (Add w32 1 N0)=0,
                    N0=1] @ const_arr1) to value 1 (./../common.c:103)

KLEE: done: total instructions = 14546
KLEE: done: completed paths = 2
KLEE: done: partially completed paths = 1
KLEE: done: generated tests = 3
ERROR: Array index is negative.
1
0
0
0
0
0
0
0
0
0
